---
booktitle: Proceedings of IJCAI 2017 Workshop on Artificial Intelligence in Affective
  Computing
publisher: PMLR
series: Proceedings of Machine Learning Research
issn: 2640-3498
volume: 66
start: 2017-08-20
end: 2017-08-20
url: http://proceedings.mlr.press
author:
  name: PMLR
location: Melbourne, Australia
published: 2017-09-15
layout: proceedings
id: AFFYCOMP2017
month: 0
cycles: false
editor:
- given: Neil
  family: Lawrence
- given: Mark
  family: Reid
title: Proceedings of Machine Learning Research
description: |
  Proceedings of IJCAI 2017 Workshop on Artificial Intelligence in Affective Computing on 20 August 2017

  Published as Volume 66 by the Proceedings of Machine Learning Research on 15 September 2017.

  Volume Edited by:
    Heath Yates
    William Hsu
    Brent Chamberlain
    Joshua Weese

  Series Editors:
    Neil D. Lawrence
    Mark Reid
date_str: 20 Aug
baseurl: "/v66"
twitter_username: MLResearchPress
github_username: mlresearch
markdown: kramdown
plugins:
- jekyll-remote-theme
remote_theme: lawrennd/proceedings
permalink: "/:title.html"
ghub:
  edit: true
  repository: v66
display:
  copy_button:
    bibtex: true
    endnote: true
    apa: true
  comments: false
email: ''
conference:
  name: IJCAI 2017 Workshop on Artificial Intelligence in Affective Computing
  url: 
  location: 
  dates:
  - 2017-08-20
analytics:
  google:
    tracking_id: UA-92432422-1
orig_bibfile: "/Users/neil/mlresearch/bibtex.bib"
# Site settings
# Original source:  /Users/neil/mlresearch/bibtex.bib
